In [2]:
import numpy as np

In [3]:
my_list=[1,2,3,4,5,6]
np.array(my_list)

array([1, 2, 3, 4, 5, 6])

In [4]:
my_list2=[[1,2,3],[4,5,6],[7,8,9]]
np.array(my_list2)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.arange(0,50)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [6]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.ones((8,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [16]:
np.linspace(0,8,15)

array([0.        , 0.57142857, 1.14285714, 1.71428571, 2.28571429,
       2.85714286, 3.42857143, 4.        , 4.57142857, 5.14285714,
       5.71428571, 6.28571429, 6.85714286, 7.42857143, 8.        ])

In [17]:
np.random.randint(1,9)

1

In [18]:
np.random.randint(1,100,20)

array([92, 20, 13, 60, 74, 99, 83, 76, 88, 98, 93,  8, 60, 62, 92, 86,  9,
       77, 21, 89])

In [20]:
arr=np.arange(0,20)

In [21]:
arr.min()

0

In [22]:
arr.max()

19

In [24]:
arr.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [26]:
arr.argmax()

19

In [27]:
arr.shape

(20,)

In [29]:
arr.dtype

dtype('int32')